### PR TITLE
make egrid style separately customizable

### PR DESCRIPTION
**Pull request by jwkaltz**
make egrid style separately customizable

C2C internal reference: GEO-3709

### CODE REVIEW

**Review by ger-benjamin — COMMENTED** [review]
I currently don't know the project.

Don't you need to add some css (here https://github.com/openoereb/oereb_client/blob/master/oereb_client/static/less/real-estate.less) ? Otheriwse you will lost the current width of columns:

```
.col-egrid-header {
  width: 25%;
}

.col-egrid-value {
  width: 75%;
}
```

Or you could keep the col-xs-# stuff and only add a class name. Then, it should be possible to override the css.

**Comment by ger-benjamin** [comment]
As discussed, I've keep the original col-xs-# classes to keep the original style.

I've added a second commit to respect the bootstrap grid (12 columns) and be sure to have two rows even with strange width customization

**Comment by jwkaltz** [comment]
@kdeininger does this change make sense to you (latest status, as proposed by @ger-benjamin )?

**Review by kdeininger — APPROVED** [review]
LGTM 👍 

Maybe you could call the CSS class simply `egrid-header`. The prefix `col-` is related to bootstrap.

**Review by kdeininger — APPROVED** [review]
👍

**Pull request merged**
